auxiliares/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', SeleccionEquipo.as_view(), name="seleccion_equipo"),
    path('consultar_cas/', CargarFluidoNuevo.as_view(), name="consultar_cas_auxiliares"),
    path('registrar_fluido_cas/', RegistrarFluidoCAS.as_view(), name="registrar_fluido_cas_auxiliares"),

    # URLs de BOMBAS
    path('bombas/', ConsultaBombas.as_view(), name="consulta_bombas"),
    path('bombas/creacion/', CreacionBomba.as_view(), name="creacion_bomba"),
    path('bombas/edicion/<int:pk>/', EdicionBomba.as_view(), name="edicion_bomba"),
    path('bombas/instalacion/creacion/<int:pk>/', CreacionInstalacionBomba.as_view(), name="creacion_instalacion_bomba"),
    path('bombas/datos_fluido/', ObtencionDatosFluidosBomba.as_view(), name="datos_fluido_bomba"),
    path('bombas/evaluaciones/<int:pk>/', ConsultaEvaluacionBomba.as_view(), name = "evaluacion_bomba"),
    path('bombas/evaluar/<int:pk>/', CreacionEvaluacionBomba.as_view(), name = "crear_evaluacion_bomba"),
    path('bombas/duplicar/<int:pk>/', DuplicarBomba.as_view(), name="duplicar_bomba"),

    path('bombas/evaluar/resultados/<int:pk>/', CalcularResultadosBomba.as_view(), name = "resultados_evaluacion_bombas"),
    path('bombas/evaluar/<int:pk>/historico/', GenerarGraficaBomba.as_view(), name='generar_historico_bomba'),


    # URLs de VENTILADORES
    path('ventiladores/', ConsultaVentiladores.as_view(), name="consulta_ventiladores"),
    path('ventiladores/creacion/', CreacionVentilador.as_view(), name="creacion_ventilador"),
    path('ventiladores/edicion/<int:pk>/', EdicionVentilador.as_view(), name="edicion_ventilador"),
    path('ventiladores/datos_fluido/', CalculoPropiedadesVentilador.as_view(), name="datos_fluido_ventilador"),
    path('ventiladores/evaluaciones/<int:pk>/', ConsultaEvaluacionVentilador.as_view(), name = "evaluaciones_ventilador"),
    path('ventiladores/evaluar/<int:pk>/', CreacionEvaluacionVentilador.as_view(), name='crear_evaluacion_ventilador'),
    path('ventiladores/evaluar/<int:pk>/resultado/', CalcularResultadosVentilador.as_view(), name='resultados_evaluacion_ventilador'),
    path('ventiladores/evaluaciones/<int:pk>/historico/', GenerarGraficaVentilador.as_view(), name='generar_historico_ventilador'),
    path('ventiladores/duplicar/<int:pk>/', DuplicarVentilador.as_view(), name="duplicar_ventilador"),

    # URLs de PRECALENTADORES DE AGUA
    path('precalentadores/', ConsultaPrecalentadoresAgua.as_view(), name="consulta_precalentadores_agua"),
    path('precalentadores/creacion/', CreacionPrecalentadorAgua.as_view(), name="creacion_precalentador_agua"),
    path('precalentadores/edicion/<int:pk>/', EdicionPrecalentadorAgua.as_view(), name="edicion_precalentador_agua"),
    path('precalentadores/duplicar/<int:pk>/', DuplicarPrecalentadorAgua.as_view(), name="duplicar_precalentador_agua"),
    path('precalentadores/corrientes/<int:pk>/', CreacionCorrientesPrecalentadorAgua.as_view(), name="creacion_corrientes_precalentador_agua"),

    path('precalentadores/evaluaciones/<int:pk>/', ConsultaEvaluacionPrecalentadorAgua.as_view(), name="evaluaciones_precalentador_agua"),
    path('precalentadores/evaluaciones/evaluar/<int:pk>/', CrearEvaluacionPrecalentadorAgua.as_view(), name="evaluar_precalentador_agua"),
    path('precalentadores/evaluaciones/grafica/<int:pk>/', GenerarGraficaPrecalentadorAgua.as_view(), name="grafica_precalentadores"),

    # URLs de PRECALENTADORES DE AGUA
    path('precalentadores-aire/', ConsultaPrecalentadorAire.as_view(), name="consulta_precalentador_aire"),
    path('precalentadores-aire/creacion/', CreacionPrecalentadorAire.as_view(), name="creacion_precalentador_aire"),
    path('precalentadores-aire/edicion/<int:pk>/', EdicionPrecalentadorAire.as_view(), name="edicion_precalentador_aire"),
    
    path('precalentadores-aire/evaluaciones/<int:pk>/', ConsultaEvaluacionPrecalentadorAire.as_view(), name="evaluaciones_precalentador_aire"),
    path('precalentadores-aire/evaluar/<int:pk>/', EvaluarPrecalentadorAire.as_view(), name="evaluar_precalentador_aire"),

    path('precalentadores-aire/evaluaciones/grafica/<int:pk>/', GenerarGraficaPrecalentadorAire.as_view(), name="grafica_precalentadores_aire"),    
    path('precalentadores-aire/duplicar/<int:pk>/', DuplicarPrecalentadorAire.as_view(), name="duplicar_precalentador_aire"),
]

calderas/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ConsultaCalderas.as_view(), name="consulta_calderas"),
    path('creacion/', CreacionCaldera.as_view(), name="creacion_caldera"),
    path('edicion/<int:pk>/', EdicionCaldera.as_view(), name="edicion_caldera"),
    path('adicionales/<int:pk>/', RegistroDatosAdicionales.as_view(), name="registro_adicionales_caldera"),

    path('unidades/', unidades_por_clase, name="unidades_por_clase"),

    path('evaluaciones/<int:pk>/', ConsultaEvaluacionCaldera.as_view(), name="evaluaciones_caldera"),
    path('evaluacion/<int:pk>/', CreacionEvaluacionCaldera.as_view(), name="evaluar_caldera"),

    path('evaluacion/<int:pk>/historico/', grafica_historica_calderas, name='generar_historico_caldera'),

    path('duplicar/<int:pk>/', DuplicarCaldera.as_view(), name="duplicar_caldera"),
]

simulaciones_pequiven/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Bienvenida.as_view(), name='bienvenida'),
    path('logout/', CerrarSesion.as_view(), name='cerrar_sesion'),
    path('login/', Login.as_view(), name='iniciar_sesion'),
    path('plantas/', PlantasPorComplejo.as_view(), name="plantas_por_complejo"),

    path('intercambiadores/', include('intercambiadores.urls')),
    path('auxiliares/', include('auxiliares.urls')),
    path('turbinas/', include('turbinas.urls')),
    path('calderas/', include('calderas.urls')),
    path('compresores/', include('compresores.urls')),

    path('usuarios/', include('usuarios.urls')),
    path('', include('pwa.urls')),
    path('manual/', ManualDeUsuario.as_view(), name="manual"),
    # path("__debug__/", include("debug_toolbar.urls")),

    path('plantas/consulta/', ConsultaPlantas.as_view(), name="consulta_plantas"),
    path('plantas/creacion/', CreacionPlanta.as_view(), name="creacion_planta"),
    path('plantas/edicion/<int:pk>', EdicionPlanta.as_view(), name="edicion_planta"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calderas/models.py
import uuid

from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator

from intercambiadores.models import Planta, Fluido, Unidades, ClasesUnidades

METODO_CHOICES = (
    ('D', 'Directo'),
    ('I', 'Indirecto'),
)

# Create your models here.

class Tambor(models.Model):
    """
    Resumen:
        Modelo que tiene la información general del tambor de la caldera

    Atributos:
        presion_operacion: models.FloatField -> Presión de operación
        temp_operacion: models.FloatField -> Temp. de Operación
        presion_diseno: models.FloatField -> Presión de diseño
        temp_diseno: models.FloatField -> Temp. de diseño
        material: models.CharField -> Material del tambor
        temperatura_unidad: Unidades -> Unidades de las magnitudes asociadas
        presion_unidad: Unidades -> Unidades de las magnitudes asociadas
    """

    presion_operacion = models.FloatField("Presión de Operación", null=True, blank = True, validators=[
        MinValueValidator(0.00001)
    ])
    temp_operacion = models.FloatField("Temperatura de Operación", null=True, blank = True, validators=[
        MinValueValidator(-273.15)
    ])
    presion_diseno = models.FloatField("Presión de Diseño", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    temp_diseno = models.FloatField("Temperatura de Diseño", null=True, blank = True, validators=[
        MinValueValidator(-273.15)
    ])
    material = models.CharField("Material del Tambor", max_length=45, null=True, blank = True)

    temperatura_unidad = models.ForeignKey(Unidades, models.PROTECT, default=1, related_name="temperatura_unidad_tambor")
    presion_unidad = models.ForeignKey(Unidades, models.PROTECT, default=33, related_name="presion_unidad_tambor")

class SeccionTambor(models.Model):
    """
    Resumen:
        Modelo que tiene la información de las dimensiones de una sección del tambor (superior o inferior)

    Atributos:
        seccion: models.CharField -> 'I' para inferior, 'S' para superior. Constante SECCIÓN
        diametro: models.FloatField -> Diámetro de la sección del tambor
        longitud: models.FloatField -> Longitud de la sección del tambor
        tambor: Tambor -> Tambor al que está asociado el lado
        dimensiones_unidad: Unidades -> Unidades de las dimensiones
    """

    SECCIONES = [
        ('I','Inferior'),
        ('S','Superior')
    ]

    seccion = models.CharField(max_length=1, choices=SECCIONES)
    diametro = models.FloatField("Diámetro", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    longitud = models.FloatField("Longitud", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    tambor = models.ForeignKey(Tambor, models.PROTECT, related_name="secciones_tambor")

    dimensiones_unidad = models.ForeignKey(Unidades, models.PROTECT, default=4)

    class Meta:
        ordering = ('seccion',)

class DimsSobrecalentador(models.Model):
    """
    Resumen:
        Modelo que tiene la información de las dimensiones del sobrecalentador.

    Atributos:
        area_total_transferencia: models.FloatField -> Área total de transferencia
        diametro_tubos: models.FloatField -> Diámetro de los tubos
        num_tubos: models.FloatField -> Número de tubos en el sobrecalentador
        area_unidad: models.FloatField -> Unidades de la propiedad correspondiente
        diametro_unidad: models.FloatField -> Unidades de la propiedad correspondiente
    """

    SECCIONES = [
        ('I','Inferior'),
        ('S','Superior')
    ]

    area_total_transferencia = models.FloatField("Área Total de Transferencia", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    diametro_tubos = models.FloatField("Diámetro de Tubos", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    num_tubos = models.IntegerField("Número de Tubos", null=True, blank = True, validators=[
        MinValueValidator(1)
    ])

    area_unidad = models.ForeignKey(Unidades, models.PROTECT, default=3, related_name="area_unidad_sobrecalentador")
    diametro_unidad = models.ForeignKey(Unidades, models.PROTECT, default=4, related_name="diametro_unidad_sobrecalentador")

class Sobrecalentador(models.Model):
    """
    Resumen:
        Modelo que tiene la información general del sobrecalentador de la caldera.

    Atributos:
        presion_operacion: models.FloatField -> Presión de operación
        temp_operacion: models.FloatField -> Temperatura de operación
        presion_diseno: models.FloatField -> Presión de diseño
        flujo_max_continuo: models.FloatField -> Flujo máximo continuo (válido para el sobrecalentador)
        dims: DimsSobrecalentador -> Dimensiones del sobrecalentador
        temperatura_unidad: Unidades -> Unidad de la magnitud correspondiente
        presion_unidad: Unidades -> Unidad de la magnitud correspondiente
        flujo_unidad: Unidades -> Unidad de la magnitud correspondiente  
    """
    presion_operacion = models.FloatField("Presión de Operación", null=True, blank=True, validators=[
        MinValueValidator(0.0001)
    ])
    temp_operacion = models.FloatField("Temperatura de Operación", null=True, blank=True, validators=[
        MinValueValidator(-273.15)
    ])
    presion_diseno = models.FloatField("Presión de Diseño", null=True, blank=True, validators=[
        MinValueValidator(0.0001)
    ])
    flujo_max_continuo = models.FloatField("Flujo Máximo Continuo", null=True, blank=True, validators=[
        MinValueValidator(0.0001)
    ])

    dims = models.OneToOneField(DimsSobrecalentador, models.PROTECT)

    temperatura_unidad = models.ForeignKey(Unidades, models.PROTECT, default=1, related_name="temperatura_unidad_sobrecalentador")
    presion_unidad = models.ForeignKey(Unidades, models.PROTECT, default=33, related_name="presion_unidad_sobrecalentador")
    flujo_unidad = models.ForeignKey(Unidades, models.PROTECT, default=6, related_name="flujo_unidad_sobrecalentador")

class DimensionesCaldera(models.Model):
    """
    Resumen:
        Modelo que tiene la información de las dimensiones de la caldera.

    Atributos:
        ancho: models.FloatField -> Ancho de la caldera
        largo: models.FloatField -> Largo de la caldera
        alto: models.FloatField -> Alto de la caldera
        dimensiones_unidad: Unidades -> Dimensión         
    """
    ancho = models.FloatField(null=True, blank=True, validators=[
        MinValueValidator(0.0001)
    ])
    largo = models.FloatField(null=True, blank=True, validators=[
        MinValueValidator(0.0001)
    ])
    alto = models.FloatField(null=True, blank=True, validators=[
        MinValueValidator(0.0001)
    ])
    dimensiones_unidad = models.ForeignKey(Unidades, models.PROTECT, default=4)

class EspecificacionesCaldera(models.Model):
    """
    Resumen:
        Modelo que contiene la información específica de las calderas.

    Atributos:
        material: models.CharField -> Material de la caldera 
        area_transferencia_calor: models.FloatField -> Área de transferencia de calor de la caldera
        area_unidad: Unidades -> Unidad del área de transferencia 
        calor_intercambiado: models.FloatField -> Calor intercambiado por la caldera
        calor_unidad: Unidades -> Unidad del calor intercambiado
        capacidad: models.FloatField -> Capacidad de la caldera 
        capacidad_unidad: Unidades -> Unidad de la capacidad de la caldera 
        temp_diseno: models.FloatField -> Temperatura de diseño
        temp_operacion: models.FloatField -> Temperatura de operación
        temperatura_unidad: models.FloatField -> Unidad de las temperaturas
        presion_diseno: models.FloatField -> Presión de diseño
        presion_operacion: models.FloatField -> Presión de operación
        presion_unidad: models.FloatField ->  Unidad de las presiones
        carga: models.FloatField -> Carga de la caldera
        carga_unidad: models.FloatField ->  Unidad de la carga de la caldera
        eficiencia_termica: models.FloatField -> Eficiencia térmica de la caldera por diseño
    """
    material = models.CharField("Material de la Caldera", max_length=45, null=True, blank = True)

    area_transferencia_calor = models.FloatField("Área de Transferencia de Calor", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    area_unidad = models.ForeignKey(Unidades, models.PROTECT, default=3, related_name="area_unidad_especificaciones")

    calor_intercambiado = models.FloatField("Calor Intercambiado", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    calor_unidad = models.ForeignKey(Unidades, models.PROTECT, default=62, related_name="calor_unidad_especificaciones")

    capacidad = models.FloatField("Capacidad de la Caldera", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    capacidad_unidad = models.ForeignKey(Unidades, models.PROTECT, default=6, related_name="capacidad_unidad_especificaciones")

    temp_diseno = models.FloatField("Temperatura de Diseño", null=True, blank = True, validators=[
        MinValueValidator(-273.15)
    ])
    temp_operacion = models.FloatField("Temperatura de Operación", null=True, blank = True, validators=[
        MinValueValidator(-273.15)
    ])
    temperatura_unidad = models.ForeignKey(Unidades, models.PROTECT, default=1, related_name="temperatura_unidad_especificaciones")

    presion_diseno = models.FloatField("Presión de Diseño", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    presion_operacion = models.FloatField("Presión de Operación", null=True, blank = True, validators=[
        MinValueValidator(0.0001)
    ])
    presion_unidad = models.ForeignKey(Unidades, models.PROTECT, default=33, related_name="presion_unidad_especificaciones")

auxiliares/templates/bombas/partials/carga_fallida.html
<form id="form" hx-swap-oob="true">
    <h3 class="text-center">No se pudo registrar la evaluación.</h3>
    <h5 class="text-center">Revise los datos ingresados e intente de nuevo más tarde</h5>
    <div class="d-flex w-100 justify-content-center">
        <a href="{% url 'evaluacion_bomba' pk=bomba.pk %}" class="btn btn-success w-50">Consultar Registro de Evaluaciones</a>
    </div>
</form>

auxiliares/templates/bombas/partials/carga_lograda.html
<form id="form" hx-swap-oob="true">
    <h3 class="text-center">¡Se ha almacenado la evaluación exitosamente!</h3>
    <div class="d-flex w-100 justify-content-center">
        <a href="{% url 'evaluacion_bomba' pk=bomba.pk %}" class="btn btn-success w-50">Consultar Registro de Evaluaciones</a>
    </div>
</form>

auxiliares/templates/bombas/partials/fluido_bomba.html
{% load l10n %}

<input required value="{{presion_vapor|unlocalize}}" hx-swap-oob="true" type="number" id="id_presion_vapor" name="presion_vapor" disabled class="form-control" step="any">
<input required value="{{viscosidad|unlocalize}}" hx-swap-oob="true" type="number" id="id_viscosidad" name="viscosidad" disabled class="form-control" step="any">
<input required value="{{densidad|unlocalize}}" hx-swap-oob="true" type="number" id="id_densidad" name="densidad" disabled class="form-control" step="any">

{% if ficha %}

<select disabled hx-swap-oob="true" name="presion_unidad" hx-include="#id_presion_succion, #id_presion_unidad, #id_fluido, #id_temperatura_operacion, #id_temperatura_unidad, #id_viscosidad_unidad, #id_densidad_unidad, #id_presion_vapor_unidad" hx-indicator="#spinner" hx-trigger="change" hx-get="/auxiliares/bombas/datos_fluido/" hx-swap="none" class="form-select" id="id_presion_unidad" disabled>
    <option {% if presion_unidad == 7 %}selected{% endif %} value="7">bar</option>
    <option {% if presion_unidad == 11 %}selected{% endif %} value="11">atm</option>
    <option {% if presion_unidad == 17 %}selected{% endif %} value="17">PSI</option>
    <option {% if presion_unidad == 22 %}selected{% endif %} value="22">mmHg</option>
    <option {% if presion_unidad == 26 %}selected{% endif %} value="26">KPa</option>
</select>

<select disabled hx-swap-oob="true" name="presion_vapor_unidad" hx-include="#id_presion_succion, #id_presion_unidad, #id_fluido, #id_temperatura_operacion, #id_temperatura_unidad, #id_viscosidad_unidad, #id_densidad_unidad, #id_presion_vapor_unidad" hx-indicator="#spinner" hx-trigger="change" hx-get="/auxiliares/bombas/datos_fluido/" hx-swap="none" class="form-select" id="id_presion_vapor_unidad" disabled>
    <option {% if presion_vapor_unidad == 7 %}selected{% endif %} value="7">bar</option>
    <option {% if presion_vapor_unidad == 11 %}selected{% endif %} value="11">atm</option>
    <option {% if presion_vapor_unidad == 17 %}selected{% endif %} value="17">PSI</option>
    <option {% if presion_vapor_unidad == 22 %}selected{% endif %} value="22">mmHg</option>
    <option {% if presion_vapor_unidad == 26 %}selected{% endif %} value="26">KPa</option>
</select>

<select disabled hx-swap-oob="true" name="temperatura_unidad" hx-include="#id_temperatura_presion_vapor, #id_presion_succion, #id_presion_unidad, #id_fluido, #id_temperatura_operacion, #id_temperatura_unidad, #id_viscosidad_unidad, #id_densidad_unidad, #id_presion_vapor_unidad" hx-indicator="#spinner" hx-trigger="change" hx-get="/auxiliares/bombas/datos_fluido/" hx-swap="none" class="form-select" id="id_temperatura_unidad">
    <option {% if temperatura_unidad == 1 %} selected {% endif %} value="1">°C</option>
    <option {% if temperatura_unidad == 2 %} selected {% endif %} value="2">K</option>
    <option {% if temperatura_unidad == 8 %} selected {% endif %} value="8">°R</option>
    <option {% if temperatura_unidad == 9 %} selected {% endif %} value="9">°F</option>
</select>

<select disabled hx-swap-oob="true" name="viscosidad_unidad" hx-include="#id_temperatura_presion_vapor, #id_presion_succion, #id_presion_unidad, #id_fluido, #id_temperatura_operacion, #id_temperatura_unidad, #id_viscosidad_unidad, #id_densidad_unidad, #id_presion_vapor_unidad" hx-indicator="#spinner" hx-trigger="change" hx-get="/auxiliares/bombas/datos_fluido/" hx-swap="none" class="form-select" id="id_viscosidad_unidad">
    <option {% if viscosidad_unidad == 35 %} selected {% endif %} value="35">cP</option>
    <option {% if viscosidad_unidad == 36 %} selected {% endif %} value="36">P</option>
    <option {% if viscosidad_unidad == 44 %} selected {% endif %} value="44">Pa.s</option> 
</select>

<select disabled hx-swap-oob="true" name="densidad_unidad" hx-include="#id_temperatura_presion_vapor, #id_presion_succion, #id_presion_unidad, #id_fluido, #id_temperatura_operacion, #id_temperatura_unidad, #id_viscosidad_unidad, #id_densidad_unidad, #id_presion_vapor_unidad" hx-indicator="#spinner" hx-trigger="change" hx-get="/auxiliares/bombas/datos_fluido/" hx-swap="none" class="form-select" id="id_densidad_unidad">
    <option {% if not densidad_unidad %} selected {% endif %} value="" selected="">---------</option>
    <option {% if densidad_unidad == 43 %} selected {% endif %} value="43">Kg/m³</option>
    <option {% if densidad_unidad == 45 %} selected {% endif %} value="45">lb/in³</option>
    <option {% if densidad_unidad == 46 %} selected {% endif %} value="46">lb/ft³</option>
    <option {% if densidad_unidad == 47 %} selected {% endif %} value="47">oz/in³</option>  
</select>

<input required disabled hx-swap-oob="true"  value="{{densidad|unlocalize}}" type="number" id="id_densidad" name="densidad" class="form-control" step="any">
<input required disabled hx-swap-oob="true" value="{{viscosidad|unlocalize}}" type="number" id="id_viscosidad" name="viscosidad" class="form-control" step="any">
<input required disabled value="{{presion_vapor|unlocalize}}" hx-swap-oob="true" type="number" id="id_presion_vapor" name="presion_vapor" class="form-control" step="any">
<input required disabled hx-swap-oob="true" value="{{presion_succion|unlocalize}}" type="number" name="presion_succion" step="any" hx-include="#id_presion_succion, #id_presion_unidad, #id_fluido, #id_temperatura_operacion, #id_temperatura_unidad, #id_viscosidad_unidad, #id_densidad_unidad, #id_presion_vapor_unidad" hx-indicator="#spinner" hx-trigger="keyup delay:1s" hx-get="/auxiliares/bombas/datos_fluido/" hx-swap="none" class="form-control" min="-273.15" id="id_presion_succion">
<input required disabled hx-swap-oob="true" value="{{temperatura_operacion|unlocalize}}" type="number" name="temperatura_operacion" step="0.01" hx-include="#id_temperatura_presion_vapor, #id_presion_succion, #id_presion_unidad, #id_fluido, #id_temperatura_operacion, #id_temperatura_unidad, #id_viscosidad_unidad, #id_densidad_unidad, #id_presion_vapor_unidad" hx-indicator="#spinner" hx-trigger="keyup delay:1s" hx-get="/auxiliares/bombas/datos_fluido/" hx-swap="none" class="form-control" min="-273.15" id="id_temperatura_operacion">

{% if not densidad or not viscosidad or not presion_vapor or not presion_succion or not temperatura_operacion %}
<button type="submit" id="submit" name="submit" value="calcular" disabled>Calcular Resultados</button>
{% endif %}

{% endif %}

<small class="text-danger" id="aviso" hx-swap-oob="true">{% if bandera %}*Los datos fueron calculados asumiendo el fluido como líquido saturado ya que la temp. de operación y presión de succión no corresponden a la fase líquido.{% endif %}</small>

auxiliares/templates/bombas/partials/tabla_evaluaciones.html
{% load static %}
{% load mathfilters %}
{% for evaluacion in object_list %}
  <tr>
    <th scope="row">
      {% if page_obj.has_previous %}
      {{ 10|mul:page_obj.previous_page_number|add:forloop.counter }}
      {% else %}
      {{ forloop.counter }}
      {% endif %}
    </th>
    <td>{{evaluacion.fecha}}</td>
    <td>{{evaluacion.nombre}}</td>
    <td>{{evaluacion.creado_por.get_full_name}}</td>
    <td>
      {% include 'bombas/modal_resultados.html' %}
      
      <button data-bs-toggle="modal" id="boton_resultados_{{evaluacion.pk}}" data-bs-target="#resultados_{{evaluacion.pk}}" class="btn btn-danger"><img width="25px" src="{% static 'img/iconos/resultados.png' %}" alt="Ícono de Resultados"></button>
    </td>
  </tr>
{% endfor %}

auxiliares/templates/bombas/partials/tabla_velocidad_lado.html
<table class="table">
    <thead>
        <tr>
            <th class="table-{{color}} text-center" colspan="6">
                FLUJOS Y VELOCIDADES DE LA {{lado.upper}}
            </th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <th class="table-dark text-center" style="vertical-align: middle;">#</th>
            <th class="table-dark text-center">DIÁMETRO INTERNO</th>
            <th class="table-dark text-center">LONGITUD TOTAL</th>
            <th class="table-dark text-center">MATERIAL TUBERÍA</th>
            <th class="table-dark text-center" style="vertical-align: middle;">VELOCIDAD</th>
            <th class="table-dark text-center">TIPO DE FLUJO</th>
        </tr>
        {% for tramo in tramos.all %}
        {% with datos_tramo=tramo.tramo %}
        <tr>
            <th class="text-center">{{forloop.counter}}</th>
            <td class="text-center">{{datos_tramo.diametro_tuberia|floatformat:2}} {{datos_tramo.diametro_tuberia_unidad}}</td>
            <td class="text-center">{{datos_tramo.longitud_tuberia|floatformat:2}} {{datos_tramo.longitud_tuberia_unidad}}</td>
            <td class="text-center"><small>{{datos_tramo.material_tuberia}}</small></td>
            <td class="text-center">{{tramo.velocidad|floatformat:2}} m/s</td>
            <td class="text-center {% if tramo.flujo == 'T' %}table-danger{% elif tramo.flujo == 'L' %}table-success{%else%}table-warning{%endif%}">
                {% if tramo.flujo == 'T' %}
                Turbulento
                {% elif tramo.flujo == 'L' %}
                Laminar
                {% else %}
                Transitorio
                {% endif %}
            </td>
        </tr>
        {% endwith %}
        {% empty %}
        <tr>
            <td colspan="6" class="text-center">
                No hay tramos registrados de este lado al momento de registrar esta evaluación.
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>